### ISSUE TITLE
Bug: date-time format not working

### ISSUE THREAD

**Issue by JohannesHepp** [OptimumCode/json-schema-validator#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am having problems validating a json with a date-time format. The validator returns true for the following input:
JsonSchema
```json
{"title":"Test","properties":{"name":{"type":"string"},"dateOfBirth":{"type":"string","format":"date-time"}}}
```
Json
```json
{"name":"Test User","dateOfBirth": "test"}
```
Running the following code returns true and does not add any issues to the list:
```kotlin
val jsonSchemaValidator = JsonSchema.fromDefinition(schema)
val json = Json.encodeToJsonElement(DummySerializer(), entry)
val result = jsonSchemaValidator.validate(json, schemaValidationErrors::add)
```

### Expected Behavior

I would expect the validator to fail on this input because the dateOfBirth property is not in the correct format.

### JSON schema

```json
{"title":"Test","properties":{"name":{"type":"string"},"dateOfBirth":{"type":"string","format":"date-time"}}}
```

### Library version

0.2.2

**Comment by OptimumCode** [comment]
Hi, @JohannesHepp

First of all, many thanks for using the library!

**TLTR:** This is expected behaviour. To achieve what you want please use the following way of creating a schema
```kotlin
import io.github.optimumcode.json.schema.FormatBehavior.ANNOTATION_AND_ASSERTION
import io.github.optimumcode.json.schema.JsonSchemaLoader
import io.github.optimumcode.json.schema.SchemaOption

val jsonSchemaValidator = JsonSchemaLoader.create()
      .withSchemaOption(SchemaOption.FORMAT_BEHAVIOR_OPTION, ANNOTATION_AND_ASSERTION)
      .fromDefinition(schema)
```
If this does not solve the problem, please let me know

**An explanation with details:**

The behaviour you observe is the expected behaviour defined by the JSON specification.
This is the link to meta-schema for [draft 2020-12](https://json-schema.org/draft/2020-12/schema) (you use it because you don't specify the `$schema` property explicitly and this draft is the latest one).
This is the part we are interested in:
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/draft/2020-12/schema",
    "$vocabulary": {
        "https://json-schema.org/draft/2020-12/vocab/core": true,
        "https://json-schema.org/draft/2020-12/vocab/applicator": true,
        "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
        "https://json-schema.org/draft/2020-12/vocab/validation": true,
        "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
        "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
        "https://json-schema.org/draft/2020-12/vocab/content": true
    },
   ...
}
```
The part that is related to your issue is `https://json-schema.org/draft/2020-12/vocab/format-annotation": true,`. It means that the format keyword only produces annotations.
To change this you can do one of the following things:
- enable format assertions in `JsonSchemaLoader` (in TLTR section)
- create a custom meta-schema that will have `https://json-schema.org/draft/2020-12/vocab/format-assertion` vocabulary enabled instead and specify this schema in the `$schema` property in your schema (this new meta-schema **must** be registered in the `JsonSchemaLoader`)
- enable vocabulary in your schema by adding the following block:
  ```json
     {
        "$vocabulary": {
          "https://json-schema.org/draft/2020-12/vocab/core": true,
          "https://json-schema.org/draft/2020-12/vocab/applicator": true,
          "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
          "https://json-schema.org/draft/2020-12/vocab/validation": true,
          "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
          "https://json-schema.org/draft/2020-12/vocab/format-assertion": true,
          "https://json-schema.org/draft/2020-12/vocab/content": true
      },
    }
  ```

**Comment by JohannesHepp** [comment]
Hey @OptimumCode thanks for your quick reply. Yes, that was exactly what I was looking for.
Did I miss that part somewhere in your documentation? JsonSchema is a really extensive definition. I missed it there. 

Probably adding a reference to this information in the _Format_ part of your README would be helpful. 
Thanks for your help. Works now.

**Comment by OptimumCode** [comment]
> Probably adding a reference to this information in the Format part of your README would be helpful.

I agree. I will add this information to the Format section in the Readme file
