### ISSUE TITLE
Register custom Keywords

### ISSUE THREAD

**Issue by colbyharrison** [OptimumCode/json-schema-validator#29]
It would be great to be able to register custom keywords. 

Playing around with this library I was able to easily create a custom keyword, but I have no way to register it. 

Thanks!

**Comment by OptimumCode** [comment]
Hi @colbyharrison,

Thank you for your interest in the library and your feedback!

Yes, creating custom keywords is quite simple because the factory interface and keyword interface have a small API exposed.

However, the library is in the stage where it supports only Draft 7 and does not yet support Draft 2019-09 (Draft 8) and 2020-12. I have started work on adding Draft 2019-09 but it is moving quite slowly, unfortunately. And the API for factory and keywords will evolve (I am not sure yet how it is going to look in the end). Because of that, I would prefer to keep this API internal until both Draft 2019-09 and 2020-12 are implemented. Otherwise, the library will have to either keep the backward compatibility for that API (that I don't want at the current stage) or the user will have to migrate the custom keywords they created once the API is changed (that is not good either).

Once Draft 2019-09 and 2020-12 are done, I would consider exposing this API to the user and allowing the registration of the custom keywords. It might be a good feature for the library.

If it is not a secret could you please add some detail about why you need to register custom keywords? It would be interesting to hear your use case.

**Comment by OptimumCode** [comment]
Thank you, @colbyharrison, for sharing the use case.
Once I add the remaining drafts I will think about how to better include this functionality in the library API.

By the way, I would like to suggest some changes in the implementation of the new keywords:

- Assertions and factories should not depend on other keywords directly (at least this is what was in my head when I decided to create this library). For example, if-else-then keywords. They depend on each other, however, neither the assertion factory nor the assertion implementation itself knows about other keywords (except the annotations other keywords might provide)
- There is an `annotation` concept. Each assertion can add an annotation to the object it currently validates:
  ```kotlin
  internal interface AssertionContext {
    fun <T : Any> annotate(key: AnnotationKey<T>, value: T)
    fun <T : Any> annotated(key: AnnotationKey<T>): T?
  }
  ```
  In your case, the `format` keyword could annotate the object with a format it expects (if the object matches this format).
  The `format*` keyword could get this annotation and perform the assertion according to the format the object has or ignore the object if there is no annotation from the `format` keyword

**Comment by colbyharrison** [comment]
Ah I missed that. Thank you @OptimumCode thats a better solution.
