### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by elect86** [OptimumCode/json-schema-validator#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Schema and json [here](https://gist.github.com/elect86/d08ffb18c1b1d64e0647cf5dc7f05638)

Validation passes with online [validator](https://www.jsonschemavalidator.net/)

```
import io.github.optimumcode.json.schema.JsonSchema
import io.github.optimumcode.json.schema.ValidationError
import io.github.optimumcode.json.schema.fromStream
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import java.io.File

fun main() {
    val schema = JsonSchema.fromStream(File("/home/elect/Downloads/SCHEMA.json").inputStream())

    val errors = mutableListOf<ValidationError>()
    val elementToValidate: JsonElement = Json.parseToJsonElement(File("/home/elect/Downloads/DATASETS.json").readText())

    println(schema.validate(elementToValidate, errors::add))

    errors.forEach { println(it) }
```

> false
ValidationError(schemaPath=/type, objectPath=, message=element is not a object, details={}, absoluteLocation=null)

### Library version

0.0.9

**Comment by OptimumCode** [comment]
Hi, @elect86. Thank you for raising this issue.

I looked at the dataset.json and schema.json you attached and cannot reproduce the problem locally. However, I have noticed that in your problem description, you have _DATASET**S**.json_ file but in the attached [github gist](https://gist.github.com/elect86/d08ffb18c1b1d64e0647cf5dc7f05638) file is called _dataset.json_. My assumption is that your file contains the dataset objects list, which is why you have this error.

Could you please check the content of the DATASETS.json file you tried to validate?

**Comment by elect86** [comment]
Sorry for the stupid mistake, you are right

My bad
